koxy-limit: 2
refy-limit: 12
perly-limit: 3
strzaly-limit: 16

gui-nazwa: "&A&LSCHOWEK"
koxy-nazwa: "&a&LKOXY: "
refy-nazwa: "&a&LREFY: "
perly-nazwa: "&a&LPERLY: "
strzaly-nazwa: "&a&LSTRZALY: "


limit-opis: " &6LIMIT: &A"
ilosc-opis: " &6POSIADASZ: &A"
